#!/usr/bin/env node
var fs      = require('fs'),
    url     = require('url'),
    http    = require('http'),
    sh      = require('shelljs'),
    yml     = require('js-yaml'),
    color   = require('colors');

// Essential Functions
var download_file_httpget = function(file_url, destination) {
    var options = {
        host: url.parse(file_url).host,
        port: url.parse(file_url).port,
        path: url.parse(file_url).pathname
    };

    var file_name;
    if(!destination) {
         file_name = url.parse(file_url).pathname.split('/').pop();
    } else {
        file_name = destination;
    }
    var file = fs.createWriteStream(destination);

    http.get(options, function(res) {
        res.on('data', function(data) {
            file.write(data);
        }).on('end', function() {
            file.end();
            console.log('File downloaded to ' + file_name);
        });
    });
};

// Noksha Started

var version = '0.0.1';
var config = 'blueprint';

// Requires git
['git'].forEach(function(dep) {
    if(!sh.which(dep)) {
        console.log(('Sorry, this script requires ' + dep).red);
        sh.exit(1);
    }
});

console.log(('noksha v' + version).blue.inverse);

try {
    var deps = require(sh.pwd() + '/' + config + '.yml');
} catch (err) {
    if(err.code === 'MODULE_NOT_FOUND') {
        console.log(('Error - No ' + config + '.yml found on the current directory').red);
    } else {
        console.log(('Check your ' + config + '.yml').red);
    }
    sh.exit(1);
}
for(var name in deps) {
    console.log(('Processing ' + name).blue);
    var dep = deps[name];
    if(dep) {
        // Prefer using git over web as a source
        if(dep.hasOwnProperty('git')) {
            console.log('Using git repo as source');
        }
        // Web
        else if(dep.hasOwnProperty('web')) {
            console.log('Using web as source');
            if(dep.hasOwnProperty('target')) {
                var path = sh.exec('dirname ' + dep.target, {silent:true}).output.trim();
                if(!sh.test('-d', path)) {
                    console.log(('Creating directory - ' + path).green);
                    sh.mkdir('-p', path);
                }
            }
            download_file_httpget(dep.web, dep.target);
        } else {
            console.log('Invalid rule'.red);
        }
    } else {
        console.log(('Invalid rule for ' + name.inverse).red);
    }
}